### ISSUE TITLE
Suggestion: Update body color

### ISSUE THREAD

**Issue by shashankgadodia** [ShashankGadodia1/github-crash-course#1]
Hello Team, 
I think if we change color of body to orange it looks better.

```css


body {
  margin: 0;
  text-align: center;
  background-color: #833927;
  color: #f6f0ee;
}

```
